/**
 * avdecc_enum.h
 *
 * Header of the avdecc_enum, which contains a numeric list of notifications.
 *
 * (c) AudioScience, Inc. 2013
 */

#pragma once
#ifndef _AVDECC_ENUM_H_
#define _AVDECC_ENUM_H_

namespace asi_avb_avdecc_enum
{
	enum aem_cmds_values
	{
		ACQUIRE_ENTITY,
		LOCK_ENTITY,
		ENTITY_AVAILABLE,
		CONTROLLER_AVAILABLE,
		READ_DESCRIPTOR,
		WRITE_DESCRIPTOR,
		SET_CONFIGURATION,
		GET_CONFIGURATION,
		SET_STREAM_FORMAT,
		GET_STREAM_FORMAT,
		SET_VIDEO_FORMAT,
		GET_VIDEO_FORMAT,
		SET_SENSOR_FORMAT,
		GET_SENSOR_FORMAT,
		SET_STREAM_INFO,
		GET_STREAM_INFO,
		SET_NAME,
		GET_NAME,
		SET_ASSOCIATION_ID,
		GET_ASSOCIATION_ID,
		SET_SAMPLING_RATE,
		GET_SAMPLING_RATE,
		SET_CLOCK_SOURCE,
		GET_CLOCK_SOURCE,
		SET_CONTROL,
		GET_CONTROL,
		INCREMENT_CONTROL,
		DECREMENT_CONTROL,
		SET_SIGNAL_SELECTOR,
		GET_SIGNAL_SELECTOR,
		SET_MIXER,
		GET_MIXER,
		SET_MATRIX,
		GET_MATRIX,
		START_STREAMING,
		STOP_STREAMING,
		REGISTER_UNSOLICITED_NOTIFICATION,
		DEREGISTER_UNSOLICITED_NOTIFICATION,
		IDENTIFY_NOTIFICATION,
		GET_AVB_INFO,
		GET_AS_PATH,
		GET_COUNTERS,
		REBOOT,
		GET_AUDIO_MAP,
		ADD_AUDIO_MAPPINGS,
		REMOVE_AUDIO_MAPPINGS,
		GET_VIDEO_MAP,
		ADD_VIDEO_MAPPINGS,
		REMOVE_VIDEO_MAPPINGS,
		GET_SENSOR_MAP,
		ADD_SENSOR_MAPPINGS,
		REMOVE_SENSOR_MAPPINGS,
		START_OPERATION,
		ABORT_OPERATION,
		OPERATION_STATUS,
		AUTH_ADD_KEY,
		AUTH_DELETE_KEY,
		AUTH_GET_KEY_LIST,
		AUTH_GET_KEY,
		AUTH_ADD_KEY_TO_CHAIN,
		AUTH_DELETE_KEY_FROM_CHAIN,
		AUTH_GET_KEYCHAIN_LIST,
		AUTH_GET_IDENTITY,
		AUTH_ADD_TOKEN,
		AUTH_DELETE_TOKEN,
		AUTHENTICATE,
		DEAUTHENTICATE,
		ENABLE_TRANSPORT_SECURITY,
		DISABLE_TRANSPORT_SECURITY,
		ENABLE_STREAM_ENCRYPTION,
		DISABLE_STREAM_ENCRYPTION,
		SET_MEMORY_OBJECT_LENGTH,
		GET_MEMORY_OBJECT_LENGTH,
		SET_STREAM_BACKUP,
		GET_STREAM_BACKUP,
		TOTAL_NUM_OF_CMDS = 75, // The total number of AEM commands currently supported in the 1722.1 specification
		AEM_CMD_ERROR = 0xffff
	};
	
	enum aem_descs_values
	{
		ENTITY,
		CONFIGURATION,
		AUDIO_UNIT,
		VIDEO_UNIT,
		SENSOR_UNIT,
		STREAM_INPUT,
		STREAM_OUTPUT,
		JACK_INPUT,
		JACK_OUTPUT,
		AVB_INTERFACE,
		CLOCK_SOURCE,
		MEMORY_OBJECT,
		LOCALE,
		STRINGS,
		STREAM_PORT_INPUT,
		STREAM_PORT_OUTPUT,
		EXTERNAL_PORT_INPUT,
		EXTERNAL_PORT_OUTPUT,
		INTERNAL_PORT_INPUT,
		INTERNAL_PORT_OUTPUT,
		AUDIO_CLUSTER,
		VIDEO_CLUSTER,
		SENSOR_CLUSTER,
		AUDIO_MAP,
		VIDEO_MAP,
		SENSOR_MAP,
		CONTROL,
		SIGNAL_SELECTOR,
		MIXER,
		MATRIX,
		MATRIX_SIGNAL,
		SIGNAL_SPLITTER,
		SIGNAL_COMBINER,
		SIGNAL_DEMULTIPLEXER,
		SIGNAL_MULTIPLEXER,
		SIGNAL_TRANSCODER,
		CLOCK_DOMAIN,
		CONTROL_BLOCK,
		TOTAL_NUM_OF_DESCS = 38, // The total number of AEM descriptors currently supproted in the 1722.1 specification
		AEM_DESC_ERROR = 0xffff
	};

	enum notifications // Notifications for the AVDECC library implementation, not part of the 1722.1 specification
	{
		NO_MATCH_FOUND = -1,

		ENDPOINT_DISCOVERED = 0,
		ENDPOINT_CONNECTED = 1,
		ENDPOINT_RECONNECTED = 2,
		ENDPOINT_DISCONNECTED = 3,	

		INVALID_COMMAND = 10,
		COMMAND_TIMEOUT = 11,
		COMMAND_RESENT = 12,
		COMMAND_SUCCESS = 13
	};
}

#endif